import type {
  TargetType,
  GeneratedProjectPlan,
  GeneratedFile,
} from "@/lib/types"
import { routingPolicy } from "./model-registry"

export interface GenerateProjectInput {
  prompt: string
  templateType?: string
  userId: string
  primaryTarget: TargetType
}

export interface GenerateProjectResult {
  plan: GeneratedProjectPlan
  files: GeneratedFile[]
  modelUsed: string
}

/**
 * Project Generator - takes a prompt and generates a project plan + files.
 * In production, this calls the selected AI model via the AI SDK.
 * For now, generates a deterministic scaffold based on the template type.
 */
export class ProjectGenerator {
  async generate(input: GenerateProjectInput): Promise<GenerateProjectResult> {
    // Select model via routing policy
    const model = await routingPolicy.chooseModel("codegen", { freeOnly: true })

    // Generate project plan based on template
    const plan = this.buildPlan(input)
    const files = this.buildFiles(input, plan)

    return {
      plan,
      files,
      modelUsed: model.modelId,
    }
  }

  private buildPlan(input: GenerateProjectInput): GeneratedProjectPlan {
    const baseName = input.prompt
      .split(" ")
      .slice(0, 4)
      .join("-")
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, "")

    return {
      name: baseName || "new-project",
      targets: [input.primaryTarget],
      pages: ["app/page.tsx", "app/layout.tsx"],
      components: ["components/header.tsx", "components/main-content.tsx"],
    }
  }

  private buildFiles(
    input: GenerateProjectInput,
    plan: GeneratedProjectPlan
  ): GeneratedFile[] {
    return [
      {
        path: "package.json",
        content: JSON.stringify(
          {
            name: plan.name,
            version: "0.1.0",
            private: true,
            scripts: { dev: "next dev", build: "next build", start: "next start" },
            dependencies: { next: "16.1.6", react: "^19", "react-dom": "^19" },
          },
          null,
          2
        ),
      },
      {
        path: "app/layout.tsx",
        content: `import type { Metadata } from "next"\nimport "./globals.css"\n\nexport const metadata: Metadata = {\n  title: "${plan.name}",\n  description: "Generated by AiBuild",\n}\n\nexport default function RootLayout({\n  children,\n}: {\n  children: React.ReactNode\n}) {\n  return (\n    <html lang="en">\n      <body>{children}</body>\n    </html>\n  )\n}`,
      },
      {
        path: "app/page.tsx",
        content: `export default function Home() {\n  return (\n    <main className="flex min-h-screen flex-col items-center justify-center p-8">\n      <h1 className="text-4xl font-bold">${plan.name}</h1>\n      <p className="mt-4 text-lg text-gray-600">Generated from: ${input.prompt.slice(0, 80)}</p>\n    </main>\n  )\n}`,
      },
      {
        path: "app/globals.css",
        content: "@tailwind base;\n@tailwind components;\n@tailwind utilities;",
      },
    ]
  }
}

export const projectGenerator = new ProjectGenerator()
