import type {
  Project,
  ProjectFile,
  Deployment,
  ModelProviderConfig,
  PromptLogEntry,
  TraceLogEntry,
  LogicFlowIssue,
} from "./types"

export const mockModels: ModelProviderConfig[] = [
  {
    id: "m1",
    name: "OpenAI",
    modelId: "gpt-4o",
    capabilities: ["code", "chat", "analysis"],
    costTier: "paid",
    enabled: true,
  },
  {
    id: "m2",
    name: "Google",
    modelId: "gemini-2.0-flash",
    capabilities: ["code", "chat"],
    costTier: "free",
    enabled: true,
  },
  {
    id: "m3",
    name: "Anthropic",
    modelId: "claude-sonnet-4-20250514",
    capabilities: ["code", "chat", "analysis"],
    costTier: "paid",
    enabled: true,
  },
  {
    id: "m4",
    name: "xAI",
    modelId: "grok-3",
    capabilities: ["code", "chat"],
    costTier: "free",
    enabled: false,
  },
  {
    id: "m5",
    name: "DeepSeek",
    modelId: "deepseek-coder",
    capabilities: ["code"],
    costTier: "free",
    enabled: true,
  },
]

export const mockProjects: Project[] = [
  {
    id: "proj_1",
    userId: "user_1",
    name: "AI Wallet App",
    slug: "ai-wallet-app",
    prompt: "Build a minimal multi-platform AI wallet app with crypto tracking and portfolio analytics.",
    templateType: "app",
    primaryTarget: "web",
    status: "deployed",
    createdAt: "2025-12-15T10:30:00Z",
    updatedAt: "2026-01-20T14:22:00Z",
  },
  {
    id: "proj_2",
    userId: "user_1",
    name: "SaaS Landing Page",
    slug: "saas-landing",
    prompt: "Create a modern SaaS landing page with pricing, features, and testimonials sections.",
    templateType: "landing",
    primaryTarget: "web",
    status: "ready",
    createdAt: "2026-01-05T08:00:00Z",
    updatedAt: "2026-01-18T11:45:00Z",
  },
  {
    id: "proj_3",
    userId: "user_1",
    name: "Task Manager Mobile",
    slug: "task-manager-mobile",
    prompt: "Build a task management mobile app with kanban boards, reminders, and team collaboration.",
    templateType: "app",
    primaryTarget: "mobile",
    status: "building",
    createdAt: "2026-01-28T16:00:00Z",
    updatedAt: "2026-02-01T09:30:00Z",
  },
  {
    id: "proj_4",
    userId: "user_1",
    name: "Admin Dashboard",
    slug: "admin-dashboard",
    prompt: "Build a comprehensive admin dashboard with user management, analytics, and settings.",
    templateType: "dashboard",
    primaryTarget: "web",
    status: "draft",
    createdAt: "2026-02-03T12:00:00Z",
    updatedAt: "2026-02-03T12:00:00Z",
  },
]

export const mockFiles: ProjectFile[] = [
  {
    id: "f1",
    projectId: "proj_1",
    path: "app/layout.tsx",
    content: `import type { Metadata } from "next"\nimport "./globals.css"\n\nexport const metadata: Metadata = {\n  title: "AI Wallet",\n  description: "AI-powered crypto wallet",\n}\n\nexport default function RootLayout({\n  children,\n}: {\n  children: React.ReactNode\n}) {\n  return (\n    <html lang="en">\n      <body>{children}</body>\n    </html>\n  )\n}`,
    language: "tsx",
    generatedBy: "ai",
    version: 1,
    createdAt: "2025-12-15T10:30:00Z",
    updatedAt: "2025-12-15T10:30:00Z",
  },
  {
    id: "f2",
    projectId: "proj_1",
    path: "app/page.tsx",
    content: `export default function Home() {\n  return (\n    <main className="flex min-h-screen flex-col items-center justify-center">\n      <h1 className="text-4xl font-bold">AI Wallet</h1>\n      <p className="mt-4 text-lg text-muted-foreground">Your intelligent crypto companion</p>\n    </main>\n  )\n}`,
    language: "tsx",
    generatedBy: "ai",
    version: 2,
    createdAt: "2025-12-15T10:30:00Z",
    updatedAt: "2026-01-10T09:00:00Z",
  },
  {
    id: "f3",
    projectId: "proj_1",
    path: "app/globals.css",
    content: `@tailwind base;\n@tailwind components;\n@tailwind utilities;`,
    language: "css",
    generatedBy: "ai",
    version: 1,
    createdAt: "2025-12-15T10:30:00Z",
    updatedAt: "2025-12-15T10:30:00Z",
  },
  {
    id: "f4",
    projectId: "proj_1",
    path: "components/wallet-card.tsx",
    content: `"use client"\n\nimport { Card } from "@/components/ui/card"\n\nexport function WalletCard({ balance }: { balance: number }) {\n  return (\n    <Card className="p-6">\n      <h2 className="text-sm text-muted-foreground">Total Balance</h2>\n      <p className="text-3xl font-bold">\${balance.toLocaleString()}</p>\n    </Card>\n  )\n}`,
    language: "tsx",
    generatedBy: "ai",
    version: 1,
    createdAt: "2025-12-15T10:30:00Z",
    updatedAt: "2025-12-15T10:30:00Z",
  },
  {
    id: "f5",
    projectId: "proj_1",
    path: "package.json",
    content: `{\n  "name": "ai-wallet-app",\n  "version": "0.1.0",\n  "private": true,\n  "scripts": {\n    "dev": "next dev",\n    "build": "next build"\n  },\n  "dependencies": {\n    "next": "16.1.6",\n    "react": "^19",\n    "react-dom": "^19"\n  }\n}`,
    language: "json",
    generatedBy: "ai",
    version: 1,
    createdAt: "2025-12-15T10:30:00Z",
    updatedAt: "2025-12-15T10:30:00Z",
  },
]

export const mockDeployments: Deployment[] = [
  {
    id: "d1",
    projectId: "proj_1",
    target: "web",
    provider: "vercel",
    providerProjectId: "prj_abc123",
    artifactUrl: "https://ai-wallet-app.vercel.app",
    status: "ready",
    logsUrl: null,
    createdAt: "2026-01-20T14:00:00Z",
    updatedAt: "2026-01-20T14:22:00Z",
  },
  {
    id: "d2",
    projectId: "proj_3",
    target: "mobile",
    provider: "github-actions",
    providerProjectId: null,
    artifactUrl: null,
    status: "building",
    logsUrl: null,
    createdAt: "2026-02-01T09:00:00Z",
    updatedAt: "2026-02-01T09:30:00Z",
  },
]

export const mockPromptLogs: PromptLogEntry[] = [
  {
    id: "pl1",
    projectId: "proj_1",
    providerId: "m2",
    modelId: "gemini-2.0-flash",
    role: "user",
    content: "Build a minimal multi-platform AI wallet app with crypto tracking and portfolio analytics.",
    createdAt: "2025-12-15T10:30:00Z",
  },
  {
    id: "pl2",
    projectId: "proj_1",
    providerId: "m2",
    modelId: "gemini-2.0-flash",
    role: "assistant",
    content: "I'll create an AI wallet app with the following structure: app/layout.tsx, app/page.tsx, components/wallet-card.tsx, components/portfolio-chart.tsx...",
    createdAt: "2025-12-15T10:30:05Z",
  },
]

export const mockTraceLogs: TraceLogEntry[] = [
  {
    id: "tl1",
    projectId: "proj_1",
    kind: "generation",
    status: "ok",
    metadata: { filesGenerated: 5, model: "gemini-2.0-flash", durationMs: 4200 },
    createdAt: "2025-12-15T10:30:05Z",
  },
  {
    id: "tl2",
    projectId: "proj_1",
    kind: "deploy",
    status: "ok",
    metadata: { target: "web", provider: "vercel", url: "https://ai-wallet-app.vercel.app" },
    createdAt: "2026-01-20T14:22:00Z",
  },
  {
    id: "tl3",
    projectId: "proj_3",
    kind: "generation",
    status: "ok",
    metadata: { filesGenerated: 12, model: "gemini-2.0-flash", durationMs: 8100 },
    createdAt: "2026-01-28T16:00:30Z",
  },
]

export const mockIssues: LogicFlowIssue[] = [
  {
    kind: "missing-check",
    path: "app/page.tsx",
    message: "No null check for wallet balance data before rendering",
    suggestion: "Add a loading state or fallback when balance is undefined",
  },
  {
    kind: "unhandled-error",
    path: "components/wallet-card.tsx",
    message: "API fetch has no error boundary or try-catch",
    suggestion: "Wrap fetch call in try-catch and show error state to user",
  },
]
